data_ingestion:
  test_size: 0.25

mongodb:
  uri: "mongodb+srv://bhardwajsourav113:hktxUj6Zkwpgc550@cluster0.x3fxayl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  database: "Proj1"
  collection: "Proj1-Data"

model_params:
  n_estimators: 100
  max_features: log2
  criterion: entropy
